MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH_T: '../../pretrainedModel/jx_vit_base_p16_224-80ecf9dd.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  RE: 1
  RE_LAYER: 1
  DIRECT: 0
  DEVICE_ID: ('0')
  BASE: 0
  G_CHANNEL: 3
INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
DATASETS:
  NAMES: ('RGBNT201')
  ROOT_DIR: '../../../dataSet/'

SOLVER:
  BASE_LR: 0.0002
  WARMUP_ITERS: 10
  IMS_PER_BATCH: 16
  EVAL_PERIOD: 10
  MAX_EPOCHS: 120
  ADV_FACTOR: 50
  ADV_MODE: 1
  LP: 8.0
  IF_CAJ: 3
  LAYER: 3
  FEAT_FACTOR: 50.0
  FEAT_FACTOR_2: 5.0
TEST:
  RE_RANKING: 'no'
  WEIGHT: './logs/RGBNT201/TOP-ReID_2/TOPReIDbest.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: "nothing"
  G_V: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_G_V.pth.tar'
  D_V: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_D_V.pth.tar'
  G_I: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_G_I.pth.tar'
  D_I: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_D_I.pth.tar'
  G_T: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_G_T.pth.tar'
  D_T: '/data4/by/reid/github/MM-reid-att/TOP/ATT_LOG/aaai_06/2g_50_0_cr_0_0_3/best_D_T.pth.tar'


OUTPUT_DIR: './ATT_LOG/test'

